version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tennisot_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tennisot_db
      MYSQL_USER: tennis_user
      MYSQL_PASSWORD: tennis_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
